### ISSUE TITLE
IllegalAccessError on 1.15.x

### ISSUE THREAD

**Issue by CGDoctor8** [ChloeDawn/FovLock#1]
Currently is crashes when trying to go into the options menu for 1.15.2
```
[03:22:00] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:613) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:989) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-minecraft-1.15.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.6+build.179.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.6+build.179.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.6+build.179.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.class_1060.method_4618(Lnet/minecraft/class_2960;)V from class io.github.chloedawn.fovlock.gui.FovLockButton
	at io.github.chloedawn.fovlock.gui.FovLockButton.renderButton(FovLockButton.java:63) ~[FovLock-4.2.0.jar:?]
	at net.minecraft.class_339.render(class_339.java:84) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_437.render(class_437.java:81) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_429.render(class_429.java:116) ~[intermediary-minecraft-1.15.2-client.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:604) ~[intermediary-minecraft-1.15.2-client.jar:?]
	... 18 more
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/28/20 3:22 AM
Description: Rendering screen

java.lang.IllegalAccessError: tried to access method net.minecraft.class_1060.method_4618(Lnet/minecraft/class_2960;)V from class io.github.chloedawn.fovlock.gui.FovLockButton
	at io.github.chloedawn.fovlock.gui.FovLockButton.renderButton(FovLockButton.java:63)
	at net.minecraft.class_339.render(class_339.java:84)
	at net.minecraft.class_437.render(class_437.java:81)
	at net.minecraft.class_429.render(class_429.java:116)
	at net.minecraft.class_757.method_3192(class_757.java:604)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.chloedawn.fovlock.gui.FovLockButton.renderButton(FovLockButton.java:63)
	at net.minecraft.class_339.render(class_339.java:84)
	at net.minecraft.class_437.render(class_437.java:81)
	at net.minecraft.class_429.render(class_429.java:116)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_429
	Mouse location: Scaled: (176, 205). Absolute: (705.000000, 819.000000)
	Screen size: Scaled: (480, 264). Absolute: (1920, 1053). Scale factor of 4.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:604)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


#@!@# Game crashed! Crash report saved to: #@!@# /mnt/Games/MultiMC/instances/Fabric 1.15.2/.minecraft/crash-reports/crash-2020-01-28_03.22.00-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
```

**Comment by ChloeDawn** [comment]
Fixed in [5.0.0](https://github.com/ChloeDawn/FovLock/releases/tag/5.0.0)
